version: "3.7"

services:
  app:
    container_name: bino
    build: .
    image: bino
    volumes:
      - .:/app
    env_file: .env.docker
    environment:
      - BINO_DISCORD_TOKEN
    depends_on:
      - db
  db:
    container_name: binodb
    image: mysql:8
    restart: always
    env_file: .env.docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
