version: "3.7"

services:
  app:
    container_name: bino
    image: golang:1.16-buster
    volumes:
      - .:/go/src/app/bino
    working_dir: /go/src/app/bino
    # command: go run main.go
    env_file: .env.docker
    ports:
      - "3000"
    depends_on:
      - db
  db:
    container_name: binodb
    image: mysql:8
    restart: always
    env_file: .env.docker
    ports:
      - 3306:3306
